export type LibraryItem = {
  id: string; title: string; author: string; category: "E-kitoblar" | "Audiokitoblar" | "Matbuot";
  genre: string; color: string; design: string; mark: string; length: string; description: string; sample: string[];
};

export const libraryItems: LibraryItem[] = [
  { id: "temur", title: "Temur tuzuklari", author: "Amir Temur", category: "E-kitoblar", genre: "Tarix · Meros", color: "#224437", design: "classic", mark: "T", length: "Tanishuv matni · 3 daqiqa", description: "Davlat boshqaruvi, intizom va adolat haqidagi tarixiy meros bilan tanishing.", sample: ["Bu asarning to‘liq matni emas, ArmTV uchun tayyorlangan qisqa tanishuv namunasidir.", "Temur tuzuklari davlat boshqaruvi va qo‘shin tuzilishiga oid qarashlarni jamlagan tarixiy manba sifatida o‘rganiladi. Unda kengash, intizom, mas’uliyat hamda har bir kishining vazifasini aniq belgilash kabi mavzular muhim o‘rin tutadi.", "Asarni o‘qishda tarixiy sharoitni hisobga olish zarur. Bugungi o‘quvchi undan rahbarlik, maslahatlashuv va qabul qilingan qaror uchun javobgarlik haqida mulohaza yuritish uchun foydalanishi mumkin.", "O‘ylab ko‘ring: mas’uliyatni aniq taqsimlash jamoaning kundalik ishiga qanday yordam beradi?"] },
  { id: "otkan", title: "O‘tkan kunlar", author: "Abdulla Qodiriy", category: "E-kitoblar", genre: "Badiiy adabiyot", color: "#7b4133", design: "arch", mark: "O‘", length: "Tanishuv matni · 3 daqiqa", description: "O‘zbek romanchiligining yorqin asari: muhabbat, qadriyatlar va tarix haqida.", sample: ["Quyidagi matn romandan ko‘chirma emas, o‘quvchi uchun yozilgan tanishuv namunasidir.", "O‘tkan kunlar romanida Otabek va Kumushning taqdiri orqali insoniy tuyg‘ular, oilaviy munosabatlar va jamiyat hayoti tasvirlanadi. Shaxsiy orzular bilan atrofdagi urf-odatlar o‘rtasidagi ziddiyat asar voqealariga chuqurlik beradi.", "Asardagi qahramonlarni baholashda ularning tanloviga sabab bo‘lgan sharoitni ham kuzating. Yozuvchining tili, suhbatlari va qahramonlar ruhiyatini ifodalash usuli o‘qish taassurotini boyitadi.", "Muhokama uchun: qahramonlarning bir-birini tinglashi voqealar rivojini qanday o‘zgartirishi mumkin edi?"] },
  { id: "vatanparvar", title: "Vatanparvar", author: "Gazeta · Namuna son", category: "Matbuot", genre: "Harbiy matbuot", color: "#c2b699", design: "paper", mark: "V", length: "Namuna son · 2 daqiqa", description: "Harbiy hayot, bilim va ma’naviyat mavzularidagi matbuot sahifasi namunasi.", sample: ["NAMUNA SON. Ushbu sahifa interfeysni namoyish qilish uchun yaratilgan; rasmiy gazeta materiali emas.", "Bilim va intizom — kundalik rivojlanishning asosi. O‘qishga ajratilgan qisqa, ammo muntazam vaqt yangi ko‘nikmalarni egallashga yordam beradi. Buning uchun shaxsiy reja tuzish, o‘rganilgan mavzuni qayta ko‘rib chiqish va uni amaliy topshiriq bilan mustahkamlash foydali.", "Kitobxonlik davrasida har bir ishtirokchi o‘qigan asaridan bir fikrni o‘rtoqlashishi mumkin. Bunday suhbatlar fikrni ravon ifodalash va turli nuqtayi nazarlarni tinglashga undaydi."] },
  { id: "armiya", title: "O‘zbekiston armiyasi", author: "Jurnal · Namuna son", category: "Matbuot", genre: "Harbiy jurnal", color: "#394b3d", design: "magazine", mark: "01", length: "Namuna son · 2 daqiqa", description: "Zamonaviy bilim, kasbiy rivojlanish va jamoaviy madaniyat haqida.", sample: ["NAMUNA SON. Bu rasmiy jurnal nashri emas, platformaning matbuot bo‘limi uchun tayyorlangan demo materialdir.", "Kasbiy rivojlanish bir martalik mashg‘ulot bilan tugamaydi. Muntazam o‘qish, tajriba almashish va bajarilgan ishni tahlil qilish ko‘nikmalarni mustahkamlaydi.", "Raqamli savodxonlik ham kundalik hayotning muhim qismidir. Manbani tekshirish, shaxsiy ma’lumotni ehtiyot qilish va onlayn muloqot odobiga rioya etish har bir foydalanuvchi uchun foydali ko‘nikmalardir."] },
  { id: "temur-audio", title: "Temur tuzuklari", author: "Amir Temur · Ovozli namuna", category: "Audiokitoblar", genre: "Tarix · Ovozli mutolaa", color: "#564a31", design: "classic", mark: "T", length: "Brauzer ovozi · 1 daqiqa", description: "Tarixiy asar haqidagi tanishuv matnining brauzer yordamida ovozli o‘qilishi.", sample: ["Bu professional audiokitob emas, brauzer ovozi yordamida o‘qiladigan tanishuv namunasidir. O‘zbekcha ovozning mavjudligi qurilmangizga bog‘liq.", "Temur tuzuklari haqida o‘rganish mas’uliyat, maslahat va intizom tushunchalari ustida o‘ylashga chorlaydi. Tarixiy manbalarni o‘qishda voqealar kechgan davr sharoitini bilish va turli manbalarni solishtirish foydali. Bu namuna platformadagi ovozli mutolaa imkoniyatini ko‘rsatish uchun tayyorlangan."] },
  { id: "raqamli", title: "Raqamli dunyo", author: "ArmTV · O‘quv qo‘llanma", category: "E-kitoblar", genre: "Texnologiya", color: "#2c4363", design: "digital", mark: "+", length: "Mini qo‘llanma · 4 daqiqa", description: "Raqamli vositalardan ongli foydalanish bo‘yicha boshlang‘ich mini qo‘llanma.", sample: ["Ushbu qisqa qo‘llanma ArmTV demo platformasi uchun yozilgan.", "Raqamli ma’lumotni baholashni manbadan boshlang. Muallif kim, ma’lumot qachon e’lon qilingan, dalillar qayerdan olingan? Bir xabarni bir nechta ishonchli manbada tekshirish xato xulosalarning oldini olishga yordam beradi.", "Har bir hisob uchun alohida, uzun parol ishlating. Ikki bosqichli tasdiqlashni yoqish hisobni qo‘shimcha himoya qiladi. Tasdiqlash kodini boshqa odamga yubormang.", "Qidiruvda aniq kalit so‘zlarni tanlang. Kerakli iborani qo‘shtirnoqqa olish, rasmiy manbalarni tanlash va sanani tekshirish foydali ma’lumotga tezroq yetib borishga yordam beradi.", "Amaliy topshiriq: yaqinda uchratgan bir xabaringizning muallifi, sanasi va asl manbasini toping."] },
];

export type Lesson = { id: string; title: string; duration: string; paragraphs: string[]; takeaway: string };
export type Course = { id: string; title: string; category: string; description: string; level: string; theme: string; icon: "language" | "code" | "ai"; lessons: Lesson[] };
export const courses: Course[] = [
  { id: "english", title: "Ingliz tili: ilk qadam", category: "Tillar", description: "Kundalik muloqot uchun eng kerakli so‘z va iboralarni o‘rganing.", level: "Boshlang‘ich", theme: "blue", icon: "language", lessons: [
    { id: "greetings", title: "Salomlashish va tanishish", duration: "4 daqiqa", paragraphs: ["Ingliz tilida suhbat odatda salomlashishdan boshlanadi. Hello — salom. Good morning — xayrli tong. Good evening — xayrli kech.", "O‘zingizni tanishtirish uchun “My name is …” (Mening ismim …) yoki “I am …” (Men …man) iborasidan foydalaning. Masalan: “My name is Aziz. I am from Uzbekistan.”", "Suhbatdoshingiz ismini so‘rash: “What is your name?” Tanishganingizdan xursand ekaningizni bildirish: “Nice to meet you.” Javob: “Nice to meet you, too.”"], takeaway: "O‘zingiz haqingizda ikki gap ayting: ismingiz va qayerdan ekaningiz. Keyin suhbatdoshingizning ismini so‘rang." },
    { id: "daily", title: "Kundalik iboralar", duration: "3 daqiqa", paragraphs: ["Please — iltimos. Thank you — rahmat. You are welcome — arzimaydi. Excuse me — kechirasiz (e’tiborni jalb qilish uchun). I am sorry — uzr so‘rayman.", "Bir gapni tushunmasangiz: “Could you repeat, please?” — Iltimos, takrorlay olasizmi? Sekinroq gapirishni so‘rash: “Could you speak slowly, please?”", "Yordam kerak bo‘lsa: “Can you help me, please?” Iboralarni ovoz chiqarib takrorlash ularni eslab qolishga yordam beradi."], takeaway: "Iltimos bilan yordam so‘rash, minnatdorlik bildirish va takrorlashni so‘rash ishtirok etgan uch gapli suhbat tuzing." },
    { id: "numbers", title: "Sonlar va vaqt", duration: "3 daqiqa", paragraphs: ["Asosiy sonlar: one — bir, two — ikki, three — uch, four — to‘rt, five — besh, six — olti, seven — yetti, eight — sakkiz, nine — to‘qqiz, ten — o‘n.", "Vaqtni so‘rash: “What time is it?” To‘liq soatni aytish: “It is nine o’clock.” — Soat to‘qqiz. “At nine” — soat to‘qqizda.", "Kun tartibi haqida: “I study at seven.” — Men soat yettida o‘qiyman. “The lesson starts at ten.” — Dars soat o‘nda boshlanadi."], takeaway: "Bir kuningizdagi uchta ishning boshlanish vaqtini ingliz tilida ayting." },
  ] },
  { id: "digital", title: "Raqamli savodxonlik", category: "Raqamli texnologiyalar", description: "Internet, ma’lumot va kundalik raqamli vositalardan samarali foydalaning.", level: "Barcha uchun", theme: "green", icon: "code", lessons: [
    { id: "search", title: "Ma’lumotni izlash va tekshirish", duration: "4 daqiqa", paragraphs: ["Yaxshi qidiruv aniq savoldan boshlanadi. Keng mavzu o‘rniga joy, vaqt va mavzuni ko‘rsating. Masalan, “kitob” o‘rniga “o‘zbek mumtoz adabiyoti elektron kutubxona” deb izlang.", "Qidiruv natijasini ochgach, muallif, nashr sanasi va asl manbani tekshiring. Sarlavha matnning mazmunini to‘liq ifodalamasligi mumkin.", "Muhim ma’lumotni mustaqil manbalar bilan solishtiring. Surat yoki iqtibos kontekstdan uzib olingan bo‘lishi mumkin; uning dastlabki e’lon qilingan joyini topishga harakat qiling."], takeaway: "Bir mavzuni tanlang. Ikki xil manbani solishtirib, ularning muallifi va e’lon sanasini yozing." },
    { id: "files", title: "Fayllarni tartibga solish", duration: "3 daqiqa", paragraphs: ["Fayl nomi uning mazmunini ochib bersin. “hujjat-yangi-2” o‘rniga “2026-09-kitobxonlik-reja” kabi izchil nomlash usulini tanlang.", "Fayllarni mavzular bo‘yicha papkalarga ajrating. Faol hujjatlar va arxivni alohida saqlang. Muhim fayllarning zaxira nusxasi bo‘lishi tasodifiy yo‘qotish oqibatini kamaytiradi.", "Ulashishdan oldin kim ko‘ra olishi va kim tahrirlay olishini tekshiring. Faqat ko‘rish yetarli bo‘lsa, tahrirlash huquqini bermang."], takeaway: "Beshta fayl uchun aniq nom va mos papka tuzilmasini rejalashtiring." },
    { id: "security", title: "Hisoblarni himoyalash", duration: "4 daqiqa", paragraphs: ["Har bir hisob uchun alohida uzun parol ishlating. Parol menejeri murakkab parollarni yaratish va saqlashga yordam beradi.", "Ikki bosqichli tasdiqlashni yoqing. Kirish kodi va tiklash kodlarini boshqalarga yubormang. Kutilmagan havola orqali parol kiritishdan oldin sayt manzilini tekshiring.", "Qurilma va dasturlarni yangilab boring. Begona qurilmada ishlagach, hisobdan chiqing. Shubhali xabar shoshilinch harakat qilishga undasa, avval boshqa yo‘l bilan tekshiring."], takeaway: "O‘zingiz foydalanadigan bir hisobning xavfsizlik sozlamalarida ikki bosqichli tasdiqlash borligini tekshiring." },
  ] },
  { id: "ai", title: "Sun’iy intellekt asoslari", category: "Sun’iy intellekt", description: "AI imkoniyatlarini tushuning va foydali so‘rovlar yozishni mashq qiling.", level: "Boshlang‘ich", theme: "purple", icon: "ai", lessons: [
    { id: "intro", title: "Sun’iy intellekt nima?", duration: "4 daqiqa", paragraphs: ["Sun’iy intellekt — ayrim vazifalarni, masalan, ma’lumotdagi qonuniyatlarni topish, matn bilan ishlash yoki tasvirlarni tasniflashni bajaruvchi kompyuter tizimlarining umumiy nomi.", "Generativ AI yangi matn, rasm yoki boshqa mazmun yaratishi mumkin. U bergan javob ravon ko‘rinsa ham, xato ma’lumot bo‘lishi ehtimoli bor. Shuning uchun javoblarni tekshirish ishning bir qismidir.", "AI g‘oya to‘plash, matn rejasini tuzish va mavzuni tushunishga yordam berishi mumkin. Natijani vazifa, manba va kontekstga mos baholash esa foydalanuvchining mas’uliyatidir."], takeaway: "Kundalik o‘qishingizda AI yordam bera oladigan ikkita vazifani yozing. Har bir natijani qanday tekshirishingizni ham belgilang." },
    { id: "prompt", title: "Aniq so‘rov yozish", duration: "4 daqiqa", paragraphs: ["Foydali so‘rov to‘rtta narsani tushuntiradi: vazifa, zarur kontekst, natija shakli va cheklovlar. “Menga til o‘rgat” juda keng so‘rovdir.", "Aniqroq misol: “Men ingliz tilini endi o‘rganyapman. Tanishish mavzusida 5 ta qisqa gap yoz. Har bir gapning o‘zbekcha tarjimasini ber va oxirida 3 ta mashq qo‘sh.”", "Birinchi javobni ko‘rib, kerakli joyini aniqlashtiring: “Ikkinchi gapni sodda so‘zlar bilan qayta yoz” yoki “Bitta amaliy misol qo‘sh.”"], takeaway: "O‘zingiz o‘rganayotgan mavzu uchun vazifa, kontekst va natija shakli ko‘rsatilgan so‘rov yozing." },
    { id: "verify", title: "Natijaga tanqidiy qarash", duration: "3 daqiqa", paragraphs: ["AI javobidagi faktlarni ishonchli asl manbalardan tekshiring. Keltirilgan kitob, maqola yoki havola haqiqatan mavjudligini tekshirish ham muhim.", "Shaxsiy yoki maxfiy ma’lumotni tashqi xizmatga kiritishdan oldin tegishli qoidalarni biling. Mashq uchun haqiqiy shaxsiy ma’lumot o‘rniga to‘qima misollar ishlating.", "Javobda taxmin bilan faktni ajrating. Tizimga “Qaysi joylar noaniq?” deb so‘rash foydali bo‘lishi mumkin, lekin bu mustaqil tekshiruvning o‘rnini bosmaydi."], takeaway: "Bir AI javobidan tekshirilishi kerak bo‘lgan uchta da’voni ajrating va ularni qanday manbadan tekshirishni yozing." },
  ] },
];

export const quizQuestions = [
  { question: "O‘zbekiston Respublikasining Davlat bayrog‘i qachon qabul qilingan?", options: ["1991-yil 1-sentabr", "1991-yil 18-noyabr", "1992-yil 8-dekabr", "1992-yil 2-iyul"], correct: 1, explanation: "O‘zbekiston Respublikasining Davlat bayrog‘i 1991-yil 18-noyabrda qabul qilingan." },
  { question: "“O‘tkan kunlar” romanining muallifi kim?", options: ["Abdulla Qodiriy", "Cho‘lpon", "Oybek", "Abdulla Oripov"], correct: 0, explanation: "O‘tkan kunlar — Abdulla Qodiriyning romani." },
  { question: "Hisob xavfsizligini oshirish uchun qaysi usul ma’qul?", options: ["Barcha hisoblarda bir xil parol", "Parolni tanishlarga yuborish", "Ikki bosqichli tasdiqlashni yoqish", "Parolni faqat ismingizdan tuzish"], correct: 2, explanation: "Ikki bosqichli tasdiqlash paroldan tashqari qo‘shimcha tasdiq talab qilib, hisob himoyasini kuchaytiradi." },
  { question: "Ingliz tilida “Tanishganimdan xursandman” qanday aytiladi?", options: ["Good night", "Thank you", "See you tomorrow", "Nice to meet you"], correct: 3, explanation: "Nice to meet you — tanishganimdan xursandman degani." },
  { question: "Internetda uchragan ma’lumotni baholashda birinchi navbatda nimaga qarash kerak?", options: ["Faqat sarlavhasiga", "Manbasi va dalillariga", "Qancha marta ulashilganiga", "Matnning uzunligiga"], correct: 1, explanation: "Manba, muallif, sana va dalillar ma’lumot ishonchliligini baholashga yordam beradi." },
  { question: "Sun’iy intellekt bergan javob bilan ishlashning to‘g‘ri usuli qaysi?", options: ["Hech tekshirmasdan qabul qilish", "Faqat uzun javoblarga ishonish", "Muhim faktlarni mustaqil manbadan tekshirish", "Har bir javobni rasmiy hujjat deb bilish"], correct: 2, explanation: "AI xato qilishi mumkin. Muhim faktlarni ishonchli mustaqil manbalardan tekshirish kerak." },
  { question: "O‘zbekistonda Vatan himoyachilari kuni qachon nishonlanadi?", options: ["14-yanvar", "9-may", "1-sentabr", "8-dekabr"], correct: 0, explanation: "Vatan himoyachilari kuni har yili 14-yanvarda nishonlanadi." },
  { question: "Jamoada samarali ishlashga qaysi odat yordam beradi?", options: ["Faqat o‘z fikrida turish", "Vazifalarni noaniq qoldirish", "Muammoni yashirish", "Vazifalarni kelishish va bir-birini tinglash"], correct: 3, explanation: "Aniq vazifalar va o‘zaro tinglash hamkorlikni yaxshilaydi." },
];

export const newsArticles = [
  { id: "reading", category: "Ma’naviyat", title: "Bir kitob — ming yangi fikr", subtitle: "Kitobxonlik uchrashuvlari qanday tashkil etiladi?", date: "14-sentabr, 2026", icon: "book", color: "green", paragraphs: ["Bu platformani namoyish qilish uchun tayyorlangan namuna maqola. Unda real tadbir haqida xabar berilmayapti.", "Kitobxonlik uchrashuvi uchun katta dastur shart emas. Bir asar, bir nechta savol va fikr almashishga tayyor kichik guruh yetarli. Har bir ishtirokchi o‘ziga ta’sir qilgan bir voqea yoki fikrni aytib berishi mumkin.", "Suhbatni “Muallif nima demoqchi?” va “Bu fikrni hayotda qayerda uchratamiz?” kabi ochiq savollar bilan boshlash foydali. Turli talqinlarni tinglash matnni chuqurroq tushunishga yordam beradi.", "ArmTV elektron kutubxonasidagi tanishuv namunalari keyingi mutolaa uchun mavzu tanlashga yordam beradi."] },
  { id: "digital", category: "Ta’lim", title: "Kelajak ko‘nikmalari bugundan boshlanadi", subtitle: "Raqamli savodxonlikni kundalik odatga aylantiring.", date: "12-sentabr, 2026", icon: "code", color: "blue", paragraphs: ["Bu platforma uchun yozilgan namuna maqola, rasmiy yangilik emas.", "Raqamli ko‘nikmalarni o‘rganishda muntazamlik muhim. Har kuni o‘n daqiqa ajratib, bitta yangi amalni mashq qilish mumkin: hujjatni tartibga solish, aniq qidiruv yozish yoki hisob xavfsizligini tekshirish.", "Kichik maqsad tanlang va hafta oxirida o‘rganganlaringizni takrorlang. Amaliy topshiriq bilimni mustahkamlaydi, bajarilgan ishlar ro‘yxati esa rivojlanishni ko‘rishga yordam beradi.", "Platformadagi boshlang‘ich raqamli savodxonlik kursi shu ko‘nikmalarni qisqa matnli darslar orqali tushuntiradi."] },
  { id: "team", category: "ArmTV hayoti", title: "Bilim birlashtiradi: jamoaviy viktorina", subtitle: "Birgalikda fikrlash va yangi narsalarni bilib olish.", date: "10-sentabr, 2026", icon: "team", color: "amber", paragraphs: ["Bu haqiqiy musobaqa natijasi emas, demo platforma uchun tayyorlangan namuna maqola.", "Jamoaviy viktorina bilimni tekshirish bilan birga, muhokama qilish va kelishib qaror chiqarishni mashq qilish imkonini beradi. Har bir savoldan keyin javob sababini tahlil qilish o‘rganishga yordam beradi.", "Platformadagi jamoa rejimida bir qurilma atrofida birgalikda savollarga javob berish mumkin. Natija qurilmada ko‘rinadi; masofaviy jamoalar yoki jonli reytingga ulanish bu namunaga kirmaydi.", "Savollar umumiy bilim, adabiyot va raqamli savodxonlik mavzularini qamrab oladi."] },
  { id: "language", category: "Ta’lim", title: "Yangi til uchun har kuni 10 daqiqa", subtitle: "Kichik mashqlar orqali muloqotga ilk qadam.", date: "8-sentabr, 2026", icon: "language", color: "purple", paragraphs: ["Bu tahririy namuna maqola bo‘lib, real tadbir yoki rasmiy dastur haqida xabar emas.", "Til o‘rganishning boshlanishida sodda va foydali iboralarni tanlang. Salomlashish, o‘zingizni tanishtirish va yordam so‘rash kundalik suhbatning asosini tashkil qiladi.", "Bir iborani o‘qib chiqish bilan cheklanmay, uni ovoz chiqarib ayting, yozing va kichik suhbatda ishlating. Ertasi kuni avvalgi iboralarni qaytarib, keyin yangisini qo‘shing.", "ArmTV ingliz tili mini kursidagi tanishuv darslari mustaqil mashq qilish uchun qisqa topshiriqlar bilan yakunlanadi."] },
];
