"use client";

import { assetPath } from "@/lib/asset-path";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, BookOpen, ChevronLeft, ChevronRight, CirclePlay, Film, GraduationCap, Play, Plus, Radio, ShieldCheck, Smile, Sparkles, Star, Trophy, Tv } from "lucide-react";
import { getMedia, media } from "@/lib/data";
import { useArmTV } from "./armtv-provider";
import { MediaCard } from "./media-pages";

const slides = [
  { kicker: "VATANPARVARLIK RUHIDAGI SARALANGAN KONTENT", title: <>VATAN UCHUN,<br/><em>XALQ UCHUN.</em></>, description: "Jasorat, sadoqat va milliy g‘urur. Qalblarni birlashtiruvchi hikoyalar — ArmTv’da.", image: assetPath("/images/hero-soldier.jpg"), id: "vatan", label: "Vatanparvarlik" },
  { kicker: "ARMTV TAVSIYA ETADI · HARBIY SERIAL", title: <>SARHADLARDA<br/><em>YURAKLAR BEDOR.</em></>, description: "Vatan tinchligini asrayotgan insonlar. Burch va do‘stlik haqidagi «Chegarachi» serialini kashf eting.", image: assetPath("/images/chegarachi.jpg"), id: "chegarachi", label: "Chegarachi" },
  { kicker: "OILA DAVRASIDA TOMOSHA QILING", title: <>HAR BIR HAYOT —<br/><em>BIR HIKOYA.</em></>, description: "Mehr, umid va hayotning go‘zal lahzalari. Yaqinlaringiz bilan yaxshi filmlar ulashing.", image: assetPath("/images/hayot.jpg"), id: "hayot", label: "Hayot" },
];
const categories = [
  { label: "Jonli TV", note: "Sevimli telekanallar", href: "/jonli-efir", icon: Tv },
  { label: "Filmlar va seriallar", note: "Unutilmas hikoyalar", href: "/filmlar", icon: Film },
  { label: "Bolalar uchun", note: "Qiziqarli sarguzashtlar", href: "/bolalar", icon: Smile },
  { label: "Kutubxona", note: "Mutolaa va ilhom", href: "/kutubxona", icon: BookOpen },
  { label: "Ta’lim", note: "Yangi bilim va ko‘nikma", href: "/talim", icon: GraduationCap },
  { label: "Test va viktorinalar", note: "O‘zingizni sinab ko‘ring", href: "/testlar", icon: Trophy },
];

export function HomePage() {
  const [slide, setSlide] = useState(0);
  const [recommendation, setRecommendation] = useState("Barchasi");
  const { profile, playMedia, toggleSaved, saved, progress } = useArmTV();
  const current = slides[slide];
  const currentMedia = getMedia(current.id)!;
  const films = media.filter((item) => item.type !== "kids" && !item.translated && (recommendation === "Barchasi" || (recommendation === "Filmlar" ? item.type === "film" : recommendation === "Seriallar" ? item.type === "serial" : item.type === "documentary")));
  const continued = media.filter((item) => (progress[item.id] || 0) > 0).slice(0, 3);
  return <div className="home-page">
    <div className="page-welcome"><div><h1>{profile ? `Xush kelibsiz, ${profile.name.split(" ")[0]}!` : "Siz uchun eng yaxshisi"}</h1><p>Tomosha qiling. O‘rganing. Ilhomlaning.</p></div><span><i/> Sizning media olamingiz</span></div>
    <section className={`hero hero-slide-${slide}`} aria-label="Tavsiya etilgan kontent"><div className="hero-art" key={current.image}><Image width={1128} height={1112} src={current.image} alt={slide === 0 ? "O‘zbekiston bayrog‘i oldidagi Vatan himoyachisi" : current.label} fetchPriority="high"/></div><div className="hero-shade"/><div className="hero-content"><div className="hero-eyebrow"><span><ShieldCheck size={14}/> ARMTV</span><i/>{current.kicker}</div><h2 key={slide}>{current.title}</h2><p>{current.description}</p><div className="hero-meta"><span><Star size={13} fill="currentColor"/> {currentMedia.rating}</span><b>HD</b><span>{currentMedia.language}</span><i/><span>{currentMedia.age}</span></div><div className="hero-actions"><button className="button button-gold" onClick={() => playMedia(current.id)}><Play size={17} fill="currentColor"/> Tomosha qilish</button><Link className="button button-glass" href={`/film/${current.id}`}>Batafsil <ArrowUpRight size={17}/></Link><button className={`hero-save ${saved.includes(current.id) ? "is-saved" : ""}`} onClick={() => toggleSaved(current.id)} aria-label={saved.includes(current.id) ? "Saqlanganlardan olib tashlash" : "Saqlanganlarga qo‘shish"}>{saved.includes(current.id) ? <ShieldCheck size={20}/> : <Plus size={21}/>}</button></div></div><div className="hero-bottom"><div className="hero-dots">{slides.map((item, index) => <button key={item.id} aria-label={`${index + 1}-banner: ${item.label}`} aria-current={slide === index ? "true" : undefined} className={slide === index ? "active" : ""} onClick={() => setSlide(index)}/>)}</div><div className="hero-slide-controls"><span><b>0{slide + 1}</b> / 03</span><button aria-label="Oldingi banner" onClick={() => setSlide((slide + 2) % 3)}><ChevronLeft size={18}/></button><button aria-label="Keyingi banner" onClick={() => setSlide((slide + 1) % 3)}><ChevronRight size={18}/></button></div></div><span className="hero-watermark">ARMTV COLLECTION</span></section>
    <section className="category-grid" aria-label="Platforma bo‘limlari">{categories.map(({ label, note, href, icon: Icon }) => <Link className="category-tile" href={href} key={href}><span className="category-icon"><Icon size={25} strokeWidth={1.5}/></span><strong>{label}</strong><span>{note}</span><ArrowUpRight className="category-arrow" size={15}/></Link>)}</section>
    <section className="recommendations"><div className="section-heading"><div><span className="eyebrow"><Sparkles size={12}/> BIRGALIKDA KASHF ETAMIZ</span><h2>Tavsiya etamiz<span className="heading-dot">.</span></h2></div><Link href="/filmlar" className="see-all">Barchasini ko‘rish <ArrowRight size={16}/></Link></div><div className="recommendation-filters" aria-label="Tavsiyalarni saralash">{["Barchasi", "Filmlar", "Seriallar", "Hujjatli"].map((filter) => <button key={filter} onClick={() => setRecommendation(filter)} className={recommendation === filter ? "active" : ""} aria-pressed={recommendation === filter}>{filter}</button>)}<span>Yaxshi hikoyalar shu yerdan boshlanadi</span></div><div className="home-media-grid">{films.map((item) => <MediaCard key={item.id} item={item}/>)}</div></section>
    <section className="live-home-banner"><span className="live-home-icon"><Radio size={30} strokeWidth={1.5}/></span><div><span className="eyebrow"><i className="live-dot"/> JONLI TELEVIDENIYE</span><h3>Sevimli telekanallaringiz. Istalgan vaqtda.</h3><p>Yangiliklar, sport, madaniyat va ko‘ngilochar dasturlar.</p></div><div className="channel-stack"><span className="channel-mini uz-channel">O‘Z<span>BEKISTON</span></span><span className="channel-mini sport-channel">SPORT</span><span className="channel-mini yoshlar-channel">YOSHLAR</span><span className="more-channels">+3</span></div><Link href="/jonli-efir" className="button button-secondary">Efirga o‘tish <ArrowUpRight size={16}/></Link></section>
    <section className="discovery-section"><div className="section-heading"><div><span className="eyebrow">HAR KUNINGIZGA YANGI MA’NO</span><h2>Tomoshadan ko‘prog‘i<span className="heading-dot">.</span></h2></div><span className="section-caption">Bilim sari bir qadam</span></div><div className="discovery-grid"><Link href="/kutubxona" className="discovery-card discovery-library"><div className="discovery-copy"><span><BookOpen size={15}/> ELEKTRON KUTUBXONA</span><h3>Yaxshi kitob —<br/>eng yaxshi hamroh.</h3><p>Mutolaa uchun vaqt toping.</p><b>Kitoblarni ko‘rish <ArrowUpRight size={16}/></b></div><div className="book-art" aria-hidden="true"><div className="decor-book book-back">VATANPARVAR</div><div className="decor-book book-front"><small>AMIR TEMUR</small><span>TEMUR<br/>TUZUKLARI</span><ShieldCheck size={37}/><i>BUYUK MEROS</i></div></div></Link><Link href="/talim" className="discovery-card discovery-education"><div className="discovery-copy"><span><GraduationCap size={16}/> TA’LIM VA RIVOJLANISH</span><h3>Bugun o‘rganing.<br/>Ertaga yuksaling.</h3><p>Tillar, texnologiyalar va AI.</p><b>Kurslarni boshlash <ArrowUpRight size={16}/></b></div><div className="education-art" aria-hidden="true"><div className="orbital orbital-one"/><div className="orbital orbital-two"/><span className="ai-chip">AI<span>YANGI IMKONIYATLAR</span></span><span className="floating-label label-code">&lt;/&gt;</span><span className="floating-label label-lang">Aa</span><span className="floating-star">✦</span></div></Link></div></section>
    {continued.length > 0 && <section className="continue-section"><div className="section-heading"><h2>Tomoshani davom ettiring</h2><span className="section-caption">Namuna lavhalari</span></div><div className="continue-grid">{continued.map((item) => <button key={item.id} className="continue-card" onClick={() => playMedia(item.id)}><Image width={90} height={104} src={item.image} alt=""/><CirclePlay size={28}/><span><strong>{item.title}</strong><small>Namuna lavhasini davom ettirish</small></span><div className="continue-progress"><i style={{width:`${Math.min((progress[item.id] / 10) * 100, 98)}%`}}/></div></button>)}</div></section>}
    <section className="kids-home-section"><div className="section-heading"><div><span className="eyebrow"><Smile size={13}/> KICHIK QAHRAMONLAR UCHUN</span><h2>Quvonchga to‘la sarguzashtlar<span className="heading-dot">.</span></h2></div><Link href="/bolalar" className="see-all">Bolalar bo‘limi <ArrowRight size={16}/></Link></div><div className="home-kids-grid">{media.filter((item) => item.type === "kids").map((item) => <Link className="kids-home-card" href={`/film/${item.id}`} key={item.id}><div><Image width={624} height={424} src={item.image} alt={item.title} loading="lazy"/><span className="kids-age">{item.age}</span><span className="kids-card-play"><Play size={20} fill="currentColor"/></span></div><h3>{item.title}</h3><p>{item.genre} <span>·</span> O‘zbekcha</p></Link>)}</div></section>
  </div>;
}
