"use client";

import { useCallback, useEffect, useId, useMemo, useRef, useState, useSyncExternalStore, type ReactNode } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, BookOpen, Bookmark, Check, CheckCircle2, ChevronRight, Clock3, Code2, Headphones, Languages, Layers3, LibraryBig, Medal, Newspaper, Play, Search, ShieldCheck, Sparkles, Square, Trophy, Users, X } from "lucide-react";
import { courses, libraryItems, newsArticles, quizQuestions, type Course, type LibraryItem } from "@/lib/learning-data";
import { normalizeSearch } from "@/lib/data";
import "./learning-pages.css";

function Modal({ title, children, onClose, wide = false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  const titleId = useId();
  useEffect(() => {
    const previousFocus = document.activeElement as HTMLElement | null;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    ref.current?.focus();
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
      if (event.key !== "Tab") return;
      const focusable = ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]), a[href], input, select, textarea, [tabindex="0"]');
      if (!focusable?.length) { event.preventDefault(); return; }
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (event.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && (document.activeElement === last || document.activeElement === ref.current)) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => { document.body.style.overflow = previousOverflow; document.removeEventListener("keydown", onKeyDown); previousFocus?.focus(); };
  }, [onClose]);
  return <div className="learn-modal-backdrop" onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}><div ref={ref} className={`learn-modal ${wide ? "learn-modal-wide" : ""}`} role="dialog" aria-modal="true" aria-labelledby={titleId} tabIndex={-1}><div className="learn-modal-top"><span className="learn-eyebrow">ARMYTV · BILIM OLAMI</span><button className="learn-icon-button" aria-label="Oynani yopish" onClick={onClose}><X size={21} /></button></div><h2 id={titleId} className="learn-modal-title">{title}</h2>{children}</div></div>;
}

function subscribeStorage(callback: () => void) { window.addEventListener("storage", callback); window.addEventListener("learn-storage", callback); return () => { window.removeEventListener("storage", callback); window.removeEventListener("learn-storage", callback); }; }
function useSavedRecord<T extends Record<string, unknown>>(key: string) {
  const read = useCallback(() => { try { return localStorage.getItem(key) || "{}"; } catch { return "{}"; } }, [key]);
  const raw = useSyncExternalStore(subscribeStorage, read, () => "{}");
  const value = useMemo(() => { try { const parsed = JSON.parse(raw); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as T : {} as T; } catch { return {} as T; } }, [raw]);
  const [temporary, setTemporary] = useState<T | null>(null);
  const save = useCallback((next: T) => { setTemporary(next); try { localStorage.setItem(key, JSON.stringify(next)); window.dispatchEvent(new Event("learn-storage")); } catch { /* The page remains usable when browser storage is unavailable. */ } }, [key]);
  return [temporary ?? value, save] as const;
}

function SectionHeading({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: ReactNode }) {
  return <div className="learn-heading"><div><p className="learn-eyebrow">{eyebrow}</p><h1>{title}<span>.</span></h1><p className="learn-description">{description}</p></div>{children}</div>;
}

function FilterTabs({ values, selected, onChange, label }: { values: string[]; selected: string; onChange: (value: string) => void; label: string }) {
  return <div className="learn-tabs" role="group" aria-label={label}>{values.map(value => <button key={value} aria-pressed={value === selected} className={value === selected ? "active" : ""} onClick={() => onChange(value)}>{value}</button>)}</div>;
}

function BookCover({ item, featured = false }: { item: LibraryItem; featured?: boolean }) {
  return <div aria-hidden="true" className={`learn-book-cover learn-book-${item.design} ${featured ? "learn-book-featured" : ""}`} style={{ "--book-color": item.color } as React.CSSProperties}><div className="learn-book-border" /><div className="learn-book-brand">{item.category === "Matbuot" ? "HARBIY MATBUOT" : "ARMYTV KUTUBXONASI"}</div><div className="learn-book-mark">{item.mark}</div><div className="learn-book-cover-title">{item.title}</div><div className="learn-book-cover-author">{item.author.split(" · ")[0]}</div><span className="learn-book-bottom">{item.category === "Matbuot" ? "NAMUNA NASHR" : "BILIM — ENG KATTA KUCH"}</span>{item.category === "Audiokitoblar" && <span className="learn-book-audio"><Headphones size={17} /></span>}</div>;
}

export function LibraryPage() {
  const [category, setCategory] = useState("Barchasi");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<LibraryItem | null>(null);
  const [speaking, setSpeaking] = useState(false);
  const [audioMessage, setAudioMessage] = useState("");
  const [saved, setSaved] = useSavedRecord<Record<string, boolean>>("armtv-library-bookmarks");
  const [onlySaved, setOnlySaved] = useState(false);
  const close = useCallback(() => { setSelected(null); setSpeaking(false); setAudioMessage(""); if (typeof window !== "undefined" && "speechSynthesis" in window) window.speechSynthesis.cancel(); }, []);
  useEffect(() => () => { if ("speechSynthesis" in window) window.speechSynthesis.cancel(); }, []);
  const filtered = libraryItems.filter(item => (category === "Barchasi" || item.category === category) && (!onlySaved || saved[item.id]) && normalizeSearch(`${item.title} ${item.author} ${item.genre}`).includes(normalizeSearch(query)));
  const playSample = () => {
    if (!selected) return;
    if (!("speechSynthesis" in window)) { setAudioMessage("Bu brauzer ovozli o‘qishni qo‘llab-quvvatlamaydi. Matnni quyida o‘qishingiz mumkin."); return; }
    if (speaking) { window.speechSynthesis.cancel(); setSpeaking(false); return; }
    const utterance = new SpeechSynthesisUtterance(selected.sample.slice(1).join(" "));
    utterance.lang = "uz-UZ"; utterance.rate = 0.85;
    utterance.onend = () => setSpeaking(false);
    utterance.onerror = () => { setSpeaking(false); setAudioMessage("Qurilmada mos ovoz topilmadi. Matnni quyida o‘qishingiz mumkin."); };
    window.speechSynthesis.speak(utterance); setSpeaking(true); setAudioMessage("Brauzer yordamida ovozli o‘qish. Talaffuz qurilmadagi ovozga bog‘liq.");
  };
  return <div className="learn-page">
    <SectionHeading eyebrow="MUTOLAA UCHUN VAQT" title="Elektron kutubxona" description="Buyuk meros, yangi g‘oyalar va siz uchun tanlangan asarlar."><div className="learn-heading-icon"><LibraryBig size={30} /></div></SectionHeading>
    <section className="learn-library-feature"><div className="learn-feature-copy"><span className="learn-label"><span /> HAFTA TAVSIYASI</span><h2>Asrlar osha<br />qadr topgan hikmat.</h2><p>Temur tuzuklari — tarixiy meros, adolat va mas’uliyat haqida o‘ylashga chorlovchi asar.</p><button className="learn-primary" onClick={() => setSelected(libraryItems[0])}><BookOpen size={17} /> Mutolaani boshlash <ArrowRight size={17} /></button><span className="learn-small-note">Asar haqida tanishuv namunasi</span></div><div className="learn-feature-book-scene"><div className="learn-orbit learn-orbit-one" /><div className="learn-orbit learn-orbit-two" /><span className="learn-feature-large-text">MEROS</span><BookCover item={libraryItems[0]} featured /><span className="learn-feature-stamp">O‘QING.<br />O‘YLANG.<br />RIVOJLANING.</span></div></section>
    <div className="learn-filter-row"><FilterTabs values={["Barchasi", "E-kitoblar", "Audiokitoblar", "Matbuot"]} selected={category} onChange={setCategory} label="Kutubxona turini tanlash" /><div className="learn-filter-actions"><button className={`learn-icon-button ${onlySaved ? "learn-saved-active" : ""}`} aria-label="Faqat saqlangan kitoblar" aria-pressed={onlySaved} onClick={() => setOnlySaved(!onlySaved)}><Bookmark size={19} fill={onlySaved ? "currentColor" : "none"} /></button><label className="learn-search"><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Kitob yoki muallifni izlash" aria-label="Kitob yoki muallifni izlash" /></label></div></div>
    <div className="learn-section-line"><h2>{onlySaved ? "Saqlangan kitoblar" : category === "Barchasi" ? "Mutolaa javoni" : category}</h2><span>{filtered.length} ta material</span></div>
    <div className="learn-book-grid">{filtered.map(item => <article className="learn-book-card" id={`kitob-${item.id}`} key={item.id}><button className="learn-book-open" onClick={() => setSelected(item)} aria-label={`${item.title} — ${item.category === "Audiokitoblar" ? "tinglash" : "o‘qish"}`}><div className="learn-book-shelf"><BookCover item={item} /><span className="learn-book-hover">{item.category === "Audiokitoblar" ? <Headphones size={18} /> : <BookOpen size={18} />} {item.category === "Audiokitoblar" ? "Tinglash" : "Mutolaa qilish"}</span></div></button><div className="learn-book-info"><p>{item.genre}</p><div><h3><button onClick={() => setSelected(item)}>{item.title}</button></h3><button className={`learn-book-save ${saved[item.id] ? "learn-saved-active" : ""}`} onClick={() => setSaved({ ...saved, [item.id]: !saved[item.id] })} aria-label={`${item.title}: ${saved[item.id] ? "saqlanganlardan olib tashlash" : "saqlash"}`} aria-pressed={!!saved[item.id]}><Bookmark size={17} fill={saved[item.id] ? "currentColor" : "none"} /></button></div><span>{item.author}</span></div></article>)}</div>
    {!filtered.length && <div className="learn-empty"><Search size={30} /><h3>Material topilmadi</h3><p>Boshqa nom bilan izlab ko‘ring yoki filtrlarni tozalang.</p><button className="learn-secondary" onClick={() => { setQuery(""); setCategory("Barchasi"); setOnlySaved(false); }}>Filtrlarni tozalash</button></div>}
    <div className="learn-note"><BookOpen size={18} /><p>Kutubxonada tanishuv uchun namuna matnlar berilgan. Saqlagan kitoblaringiz shu brauzerda eslab qolinadi.</p></div>
    {selected && <Modal title={selected.title} onClose={close}><div className="learn-reading-meta"><span>{selected.author}</span><span><Clock3 size={14} />{selected.length}</span></div>{selected.category === "Audiokitoblar" && <div className="learn-audio-panel"><Headphones size={26} /><div><strong>Ovozli tanishuv namunasi</strong><p>Matn brauzer ovozi bilan o‘qiladi.</p></div><button className="learn-primary" onClick={playSample}>{speaking ? <Square size={16} /> : <Play size={16} />}{speaking ? "To‘xtatish" : "Tinglash"}</button></div>}{audioMessage && <p className="learn-status" role="status">{audioMessage}</p>}<div className="learn-reading-text">{selected.sample.map((paragraph, index) => <p key={index} className={index === 0 ? "learn-demo-notice" : ""}>{paragraph}</p>)}</div><button className="learn-secondary" onClick={() => setSaved({ ...saved, [selected.id]: !saved[selected.id] })}><Bookmark size={17} fill={saved[selected.id] ? "currentColor" : "none"} />{saved[selected.id] ? "Saqlanganlardan olib tashlash" : "Keyinroq o‘qish uchun saqlash"}</button></Modal>}
  </div>;
}

function CourseIcon({ icon, size = 48 }: { icon: Course["icon"]; size?: number }) { return icon === "language" ? <Languages size={size} /> : icon === "code" ? <Code2 size={size} /> : <Sparkles size={size} />; }

export function CoursesPage() {
  const [category, setCategory] = useState("Barchasi");
  const [selected, setSelected] = useState<Course | null>(null);
  const [lessonIndex, setLessonIndex] = useState(0);
  const [completed, setCompleted] = useSavedRecord<Record<string, boolean>>("armtv-course-progress");
  const close = useCallback(() => setSelected(null), []);
  const count = (course: Course) => course.lessons.filter(lesson => completed[`${course.id}:${lesson.id}`]).length;
  const completedTotal = courses.reduce((total, course) => total + count(course), 0);
  const totalLessons = courses.reduce((total, course) => total + course.lessons.length, 0);
  const filtered = courses.filter(course => category === "Barchasi" || course.category === category);
  const lesson = selected?.lessons[lessonIndex];
  const openCourse = (course: Course) => { const firstIncomplete = course.lessons.findIndex(item => !completed[`${course.id}:${item.id}`]); setLessonIndex(Math.max(firstIncomplete, 0)); setSelected(course); };
  return <div className="learn-page"><SectionHeading eyebrow="HAR KUNI BIR QADAM OLDINGA" title="Bilimingizga sarmoya" description="Yangi ko‘nikmalarni o‘zlashtiring. O‘z sur’atingizda o‘rganing."><div className="learn-heading-icon"><Layers3 size={30} /></div></SectionHeading>
    <section className="learn-course-banner"><div><span className="learn-label"><span /> SIZNING RIVOJLANISH YO‘LINGIZ</span><h2>Kichik qadamlar.<br /><em>Katta imkoniyatlar.</em></h2><p>Qisqa matnli darslar va amaliy mashqlar bilan yangi bilimlarni kundalik odatga aylantiring.</p></div><div className="learn-progress-card"><div className="learn-progress-card-top"><span><ShieldCheck size={19} /> Shaxsiy o‘sish</span><span>{Math.round(completedTotal / totalLessons * 100)}%</span></div><strong>{completedTotal}<span> / {totalLessons}</span></strong><p>dars yakunlandi</p><div className="learn-progress-track"><span style={{ width: `${completedTotal / totalLessons * 100}%` }} /></div><span className="learn-progress-caption">Natija shu brauzerda saqlanadi</span></div></section>
    <div className="learn-filter-row"><FilterTabs values={["Barchasi", "Tillar", "Raqamli texnologiyalar", "Sun’iy intellekt"]} selected={category} onChange={setCategory} label="Kurs yo‘nalishi" /><span className="learn-result-count">{filtered.length} ta mini kurs</span></div>
    <div className="learn-course-grid">{filtered.map((course, index) => { const done = count(course); return <article key={course.id} id={`kurs-${course.id}`} className="learn-course-card"><button className={`learn-course-art learn-art-${course.theme}`} onClick={() => openCourse(course)} aria-label={`${course.title} kursini ochish`}><span className="learn-course-level">{course.level}</span><div className="learn-art-grid" /><div className="learn-course-orb"><CourseIcon icon={course.icon} size={58} /></div><span className="learn-course-art-caption">{course.icon === "language" ? "HELLO, WORLD." : course.icon === "code" ? "EXPLORE. LEARN. CREATE." : "THE FUTURE IS YOURS."}</span><span className="learn-course-number">0{index + 1}</span></button><div className="learn-course-body"><span className="learn-eyebrow">{course.category}</span><h2><button onClick={() => openCourse(course)}>{course.title}</button></h2><p>{course.description}</p><div className="learn-course-meta"><span><BookOpen size={15} />{course.lessons.length} ta dars</span><span><Clock3 size={15} />10–12 daqiqa</span></div>{done > 0 && <div className="learn-course-inline-progress"><div className="learn-progress-track"><span style={{ width: `${done / course.lessons.length * 100}%` }} /></div><span>{done}/{course.lessons.length} dars</span></div>}<button className={`learn-course-cta ${done === course.lessons.length ? "learn-course-finished" : ""}`} onClick={() => openCourse(course)}>{done === course.lessons.length ? <><CheckCircle2 size={17} /> Kursni takrorlash</> : done ? "O‘rganishda davom etish" : "O‘rganishni boshlash"}<ArrowRight size={17} /></button></div></article>; })}</div>
    <div className="learn-learning-tips"><div><span>01</span><h3>O‘zingizga qulay vaqtda</h3><p>Har bir dars bir necha daqiqa. Tanaffusda ham yangi bilim olish mumkin.</p></div><div><span>02</span><h3>Amaliyot bilan mustahkamlang</h3><p>Dars yakunidagi kichik topshiriqni bajaring va o‘rganganingizni qo‘llang.</p></div><div><span>03</span><h3>Natijangizni kuzating</h3><p>Tugallangan darslarni belgilang. Keyingi safar shu joydan davom eting.</p></div></div>
    {selected && lesson && <Modal title={selected.title} onClose={close} wide><div className="learn-lesson-layout"><aside className="learn-lesson-sidebar"><p>KURS DASTURI</p>{selected.lessons.map((item, index) => <button key={item.id} className={index === lessonIndex ? "active" : ""} aria-current={index === lessonIndex ? "step" : undefined} onClick={() => setLessonIndex(index)}><span className={`learn-lesson-number ${completed[`${selected.id}:${item.id}`] ? "done" : ""}`}>{completed[`${selected.id}:${item.id}`] ? <Check size={14} /> : String(index + 1).padStart(2, "0")}</span><span><strong>{item.title}</strong><small>{item.duration}</small></span></button>)}<span className="learn-lesson-save-note"><Bookmark size={14} /> Jarayon shu brauzerda saqlanadi</span></aside><div className="learn-lesson-content" key={lesson.id}><div className="learn-lesson-kicker">{lessonIndex + 1}-DARS <span><Clock3 size={13} />{lesson.duration}</span></div><h3>{lesson.title}</h3>{lesson.paragraphs.map((paragraph, index) => <p key={index}>{paragraph}</p>)}<div className="learn-exercise"><span><Sparkles size={16} /> MUSTAQIL MASHQ</span><p>{lesson.takeaway}</p></div><div className="learn-lesson-actions"><button className="learn-primary" disabled={!!completed[`${selected.id}:${lesson.id}`]} onClick={() => setCompleted({ ...completed, [`${selected.id}:${lesson.id}`]: true })}>{completed[`${selected.id}:${lesson.id}`] ? <CheckCircle2 size={17} /> : <Check size={17} />}{completed[`${selected.id}:${lesson.id}`] ? "Dars yakunlangan" : "Darsni yakunlash"}</button>{lessonIndex < selected.lessons.length - 1 && <button className="learn-text-button" onClick={() => setLessonIndex(lessonIndex + 1)}>Keyingi dars <ArrowRight size={16} /></button>}</div>{count(selected) === selected.lessons.length && <div className="learn-completion" role="status"><Medal size={23} /><div><strong>Mini kursni yakunladingiz!</strong><p>Bilimingizni amaliyotda qo‘llab, mustahkamlashda davom eting.</p></div></div>}</div></div></Modal>}
  </div>;
}

export function QuizPage() {
  const [mode, setMode] = useState("Yakka tartibda");
  const [teamName, setTeamName] = useState("");
  const [stage, setStage] = useState<"intro" | "quiz" | "result">("intro");
  const [questionIndex, setQuestionIndex] = useState(0);
  const [answers, setAnswers] = useState<(number | null)[]>(Array(quizQuestions.length).fill(null));
  const [review, setReview] = useState(false);
  const [saved, setSaved] = useSavedRecord<Record<string, number>>("armtv-quiz-best");
  const questionRef = useRef<HTMLHeadingElement>(null);
  const resultRef = useRef<HTMLDivElement>(null);
  const current = quizQuestions[questionIndex];
  const score = answers.reduce<number>((total, answer, index) => total + (answer === quizQuestions[index].correct ? 1 : 0), 0);
  const bestKey = mode === "Yakka tartibda" ? "individual" : "team";
  const best = typeof saved[bestKey] === "number" ? saved[bestKey] : 0;
  const reset = () => { setStage("intro"); setAnswers(Array(quizQuestions.length).fill(null)); setQuestionIndex(0); setReview(false); };
  const navigate = (next: number) => { setQuestionIndex(next); setTimeout(() => questionRef.current?.focus(), 0); };
  const finish = () => { setSaved({ ...saved, [bestKey]: Math.max(score, best) }); setStage("result"); setTimeout(() => resultRef.current?.focus(), 0); };
  return <div className="learn-page"><SectionHeading eyebrow="BILIMINGIZNI SINAB KO‘RING" title="Zakovat maydoni" description="Savollarga javob bering, yangi bilimlarni kashf eting va o‘zingizni rivojlantiring."><div className="learn-heading-icon"><Trophy size={30} /></div></SectionHeading><div className="learn-quiz-layout"><div className="learn-quiz-main">
    {stage === "intro" && <><FilterTabs values={["Yakka tartibda", "Jamoa bilan"]} selected={mode} onChange={setMode} label="Viktorina rejimi" /><section className="learn-quiz-intro"><div className="learn-quiz-trophy"><Trophy size={63} /><span className="learn-trophy-star learn-trophy-star-one">✦</span><span className="learn-trophy-star learn-trophy-star-two">✦</span><div /></div><span className="learn-label">BILIM — SIZNING KUCHINGIZ</span><h2>{mode === "Jamoa bilan" ? "Birgalikda yanada kuchli." : "Bugun o‘zingizni sinang."}</h2><p>{mode === "Jamoa bilan" ? "Jamoangiz bilan bir qurilmada muhokama qiling va javobni birgalikda tanlang. Bu mahalliy demo, onlayn bellashuv emas." : "Tarix, adabiyot, tillar va raqamli bilimlar. Har bir savol — yangi narsani o‘rganish uchun imkoniyat."}</p><div className="learn-quiz-facts"><span><Layers3 size={17} /><strong>8 ta</strong> savol</span><span><Clock3 size={17} /><strong>~5</strong> daqiqa</span><span><Medal size={17} /><strong>8</strong> maksimal ball</span></div>{mode === "Jamoa bilan" && <label className="learn-team-field">Jamoa nomi<input value={teamName} onChange={event => setTeamName(event.target.value)} placeholder="Masalan, Bilimdonlar" maxLength={40} /></label>}<button className="learn-primary learn-quiz-start" disabled={mode === "Jamoa bilan" && !teamName.trim()} onClick={() => { setStage("quiz"); setTimeout(() => questionRef.current?.focus(), 0); }}>Viktorinani boshlash <ArrowRight size={18} /></button><span className="learn-small-note">Vaqt chegaralanmagan · Yakunda javoblar tahlili</span></section></>}
    {stage === "quiz" && <section className="learn-question-card"><div className="learn-question-top"><span>{mode === "Jamoa bilan" ? teamName : "Umumiy bilimlar"}</span><strong>{questionIndex + 1}<span> / {quizQuestions.length}</span></strong></div><div className="learn-question-dots" aria-label={`${answers.filter(answer => answer !== null).length} ta savolga javob berildi`}>{quizQuestions.map((_, index) => <button key={index} onClick={() => navigate(index)} className={`${answers[index] !== null ? "answered" : ""} ${index === questionIndex ? "current" : ""}`} aria-label={`${index + 1}-savol${answers[index] !== null ? ", javob berilgan" : ""}`} aria-current={index === questionIndex ? "step" : undefined} />)}</div><p className="learn-eyebrow">{questionIndex + 1}-SAVOL</p><h2 ref={questionRef} tabIndex={-1}>{current.question}</h2><div className="learn-answer-options" role="group" aria-label="Javobni tanlang">{current.options.map((option, index) => <button key={`${questionIndex}-${index}`} className={answers[questionIndex] === index ? "selected" : ""} aria-pressed={answers[questionIndex] === index} onClick={() => setAnswers(answers.map((answer, i) => i === questionIndex ? index : answer))}><span>{String.fromCharCode(65 + index)}</span><strong>{option}</strong><span className="learn-answer-radio">{answers[questionIndex] === index && <Check size={13} />}</span></button>)}</div><div className="learn-question-controls"><button className="learn-text-button" disabled={questionIndex === 0} onClick={() => navigate(questionIndex - 1)}><ArrowLeft size={16} /> Oldingi</button>{questionIndex === quizQuestions.length - 1 ? <button className="learn-primary" disabled={answers.some(answer => answer === null)} onClick={finish}>Natijani ko‘rish <Trophy size={17} /></button> : <button className="learn-primary" disabled={answers[questionIndex] === null} onClick={() => navigate(questionIndex + 1)}>Keyingi savol <ArrowRight size={17} /></button>}</div>{questionIndex === quizQuestions.length - 1 && answers.some(answer => answer === null) && <p className="learn-status">Natijani olish uchun barcha savollarga javob bering. Yuqoridagi belgilar orqali savolga qayting.</p>}<button className="learn-quiz-exit" onClick={reset}>Viktorinadan chiqish</button></section>}
    {stage === "result" && <section className="learn-result" ref={resultRef} tabIndex={-1}><div className="learn-result-icon"><Trophy size={42} /></div><p className="learn-eyebrow">{mode === "Jamoa bilan" ? `${teamName} · JAMOA NATIJASI` : "SIZNING NATIJANGIZ"}</p><h2>{score >= 6 ? "Ajoyib natija!" : score >= 4 ? "Yaxshi boshlanish!" : "Har bir urinish — yangi bilim."}</h2><div className="learn-score">{score}<span>/{quizQuestions.length}</span></div><p>{quizQuestions.length} ta savoldan {score} tasiga to‘g‘ri javob berdingiz.</p><div className="learn-result-stats"><span><CheckCircle2 size={19} /><strong>{score}</strong> To‘g‘ri javob</span><span><Trophy size={19} /><strong>{Math.max(best, score)}</strong> Eng yaxshi natija</span></div><div className="learn-result-actions"><button className="learn-primary" onClick={reset}>Qayta sinab ko‘rish <ArrowRight size={17} /></button><button className="learn-secondary" onClick={() => setReview(!review)} aria-expanded={review}>Javoblarni {review ? "yashirish" : "tahlil qilish"} <ArrowDown size={16} /></button></div>{review && <div className="learn-review">{quizQuestions.map((question, index) => <article key={question.question}><div className={`learn-review-status ${answers[index] === question.correct ? "correct" : "incorrect"}`}>{answers[index] === question.correct ? <Check size={15} /> : <X size={15} />}</div><div><h3>{index + 1}. {question.question}</h3><p>Sizning javobingiz: <strong>{answers[index] !== null ? question.options[answers[index]!] : "Javob berilmagan"}</strong></p>{answers[index] !== question.correct && <p className="learn-correct-answer">To‘g‘ri javob: {question.options[question.correct]}</p>}<p className="learn-review-explanation">{question.explanation}</p></div></article>)}</div>}</section>}
    </div><aside className="learn-quiz-sidebar"><div className="learn-personal-best"><span><Medal size={19} /> SHAXSIY REKORD</span><strong>{best}<span> / 8</span></strong><p>{best > 0 ? "Shu brauzerdagi eng yaxshi natijangiz. Davom eting!" : "Birinchi viktorinangizni yakunlab, rekordingizni o‘rnating."}</p></div><div className="learn-leaderboard"><div className="learn-sidebar-title"><h2>Bilimdonlar safi</h2><span>NAMUNA</span></div><p>Reyting ko‘rinishi uchun namunaviy ma’lumotlar.</p>{[{ name: "Bilimdonlar", initials: "BI", score: 8, color: "gold" }, { name: "Zukko yoshlar", initials: "ZY", score: 7, color: "blue" }, { name: "Kelajak", initials: "KE", score: 6, color: "green" }].map((team, index) => <div className="learn-leaderboard-row" key={team.name}><span className="learn-ranking">{String(index + 1).padStart(2, "0")}</span><span className={`learn-avatar learn-avatar-${team.color}`}>{team.initials}</span><strong>{team.name}</strong><span>{team.score}<small> ball</small></span></div>)}</div><div className="learn-quiz-tip"><Sparkles size={22} /><h3>Bilim ulashilganda ortadi.</h3><p>Viktorinadan so‘ng yangi o‘rgangan bir fikringizni do‘stingiz bilan ulashing.</p></div></aside></div></div>;
}

export function NewsPage() {
  const [category, setCategory] = useState("Barchasi");
  const [selected, setSelected] = useState<(typeof newsArticles)[number] | null>(null);
  const close = useCallback(() => setSelected(null), []);
  const filtered = newsArticles.filter(article => category === "Barchasi" || article.category === category);
  const ArticleIcon = ({ name, size = 48 }: { name: string; size?: number }) => name === "book" ? <BookOpen size={size} /> : name === "code" ? <Code2 size={size} /> : name === "team" ? <Users size={size} /> : <Languages size={size} />;
  return <div className="learn-page"><SectionHeading eyebrow="ARMYTV BILAN HAMNAFAS" title="Yangiliklar va maqolalar" description="Ma’naviyat, ta’lim va kundalik rivojlanish haqida foydali mutolaa."><div className="learn-heading-icon"><Newspaper size={30} /></div></SectionHeading><div className="learn-news-disclaimer"><span className="learn-live-dot" />NAMUNA NASHRLAR<span>Ushbu bo‘limdagi maqolalar namuna sifatida tayyorlangan.</span></div><div className="learn-filter-row"><FilterTabs values={["Barchasi", "Ma’naviyat", "Ta’lim", "ArmyTv hayoti"]} selected={category} onChange={setCategory} label="Yangilik mavzusi" /><span className="learn-result-count">{filtered.length} ta maqola</span></div><div className="learn-news-grid">{filtered.map((article, index) => <article key={article.id} className={`learn-news-card ${index === 0 && category === "Barchasi" ? "learn-news-featured" : ""}`}><button className={`learn-news-art learn-art-${article.color}`} aria-label={`${article.title} maqolasini o‘qish`} onClick={() => setSelected(article)}><div className="learn-art-grid" /><span className="learn-news-art-brand">ARMYTV<span>JURNAL</span></span><div className="learn-news-art-symbol"><ArticleIcon name={article.icon} size={76} /></div><span className="learn-news-art-word">{article.icon === "book" ? "MUTOLAA" : article.icon === "code" ? "KELAJAK" : article.icon === "team" ? "BIRLIKDAMIZ" : "YANGI QADAM"}</span><span className="learn-news-art-tag">{article.category}</span></button><div className="learn-news-body"><div className="learn-news-meta"><span>{article.category}</span><span>{article.date} · Namuna</span></div><h2><button onClick={() => setSelected(article)}>{article.title}</button></h2><p>{article.subtitle}</p><button className="learn-text-button" onClick={() => setSelected(article)}>Batafsil o‘qish <ChevronRight size={17} /></button></div></article>)}</div>{selected && <Modal title={selected.title} onClose={close}><div className="learn-reading-meta"><span>{selected.category}</span><span>{selected.date} · Namuna</span></div><p className="learn-article-subtitle">{selected.subtitle}</p><div className="learn-reading-text">{selected.paragraphs.map((paragraph, index) => <p key={index} className={index === 0 ? "learn-demo-notice" : ""}>{paragraph}</p>)}</div></Modal>}</div>;
}
